name = "demo-rolex"
compatibility_date = "2024-03-11"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
cwd = "."
dist = ".next"

[site]
bucket = ".next"
entry-point = "."

[env.production]
name = "demo-rolex-prod"

[env.staging]
name = "demo-rolex-staging"

# Add the pages build output directory
pages_build_output_dir = ".next" 